//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZeroOne.Domain
{
    using System;
    using System.Collections.Generic;
    
    public class Dining
    {
        public int Id { get; set; }
        public int FoodId { get; set; }
        public int PropertyId { get; set; }
        public decimal Price { get; set; }
        public string MealType { get; set; }
    }
}
