//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZeroOne.Domain
{
    using System;
    using System.Collections.Generic;
    
    public  class EmailAttachment
    {
        public int Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public string AttachmentPath { get; set; }
        public byte[] Attachment { get; set; }
    }
}
