//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZeroOne.Domain
{
    using System;
    using System.Collections.Generic;
    
    public  class EmailNotification
    {
        public int Id { get; set; }
        public System.Guid UniqueId { get; set; }
        public int EmployeeId { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string FromUserName { get; set; }
        public string FromPassword { get; set; }
        public Nullable<int> MailPort { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public bool IsSend { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
