//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZeroOne.Domain
{
    using System;
    using System.Collections.Generic;
    
    public  class Invoice
    {
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public int CompanyId { get; set; }
        public int VisitorId { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public decimal BillAmount { get; set; }
        public System.DateTime BookedDate { get; set; }
        public int PaidBy { get; set; }
        public bool PaymentMade { get; set; }
        public decimal Commision { get; set; }
    }
}
