//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZeroOne.Domain
{
    using System;
    using System.Collections.Generic;
    
    public  class Place
    {
        public int Id { get; set; }
        public int PropertyId { get; set; }
        public string PlaceName { get; set; }
        public decimal Distance { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public string TimeTake { get; set; }
        public int TravelBy { get; set; }
        public int PoiId { get; set; }
        public string Description { get; set; }
    }
}
